version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: appointment_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=students_db;User=root;Password=;
    ports:
      - "5001:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
